import { checkZip } from './zip.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { Document,Packer,zipSync,unzipSync,strToU8,strFromU8,xml,all,xtext,escape as e } from './runtime.mjs';
import { generate,analyze,tokens,W,R,PR } from './document.mjs';
const readPackage=async file=>{const bytes=await fs.readFile(file);return checkZip(bytes,unzipSync(bytes));};
const readXml=(files,name)=>{if(!files[name])throw new Error(`DOCX package is missing ${name}.`);return xml(strFromU8(files[name]));};
export async function owned(file){try {return all(readXml(await readPackage(file),'docProps/core.xml'),'cp:keywords').some(n=>n.textContent.includes('html2doc-skill'));}catch{return false;}}
const count=(doc,name)=>all(doc,name).length;
export function coverage(a,b){if(!a.length)return 1;const counts=new Map();for(const t of b)counts.set(t,(counts.get(t)||0)+1);let n=0;for(const t of a)if(counts.get(t)){n++;counts.set(t,counts.get(t)-1);}return n/a.length;}
const pairs=a=>a.slice(1).map((v,i)=>JSON.stringify([a[i],v]));
export async function validate(source,file){source=path.resolve(source);file=path.resolve(file);const files=await readPackage(file),doc=readXml(files,'word/document.xml'),styles=readXml(files,'word/styles.xml'),settings=readXml(files,'word/settings.xml'),rels=readXml(files,'word/_rels/document.xml.rels');
 for(const [name,payload] of Object.entries(files))if(name.endsWith('.xml')||name.endsWith('.rels'))xml(strFromU8(payload));
 const a=analyze(source),findings=[];const error=(code,message,details)=>findings.push({severity:'error',code,message,...(details?{details}:{})});
 const paragraphs=all(doc,'w:p'),styleOf=p=>all(p,'w:pStyle')[0]?.getAttribute('w:val')||'';
 const content=paragraphs.filter(p=>!styleOf(p).startsWith('ScriptaTOC')&&!(styleOf(p)==='TOCHeading'&&(!a.toc||!['nav','table'].includes(a.toc.name)))).map(xtext);
 for(const kind of ['footnote','endnote'])if(files[`word/${kind}s.xml`])content.push(xtext(readXml(files,`word/${kind}s.xml`)));
 const out=tokens(content.join(' ')),cov=coverage(a.sourceTokens,out),order=coverage(pairs(a.sourceTokens),pairs(out));
 if(cov<.995)error('text-coverage',`Semantic text coverage ${(cov*100).toFixed(2)}% is below 99.5%.`);if(order<.98)error('text-order',`Token order ${(order*100).toFixed(2)}% is below 98%.`);
 if(all(doc,'w:instrText').some(n=>/\bTOC\b/.test(n.textContent))||xtext(doc).includes('Update field to build'))error('toc-placeholder','Dynamic TOC or placeholder found.');
 if(!count(settings,'w:updateFields'))error('field-update-missing','Fields must refresh on open.');
 if(!all(styles,'w:style').some(n=>/^Heading/.test(n.getAttribute('w:styleId'))))error('heading-styles-missing','Heading styles missing.');
 if(!(await owned(file)))error('ownership-marker','Ownership marker missing.');
 const metric={headings:a.headings.length,bookmarks:count(doc,'w:bookmarkStart'),hyperlinks:count(doc,'w:hyperlink'),images:count(doc,'w:drawing'),tables:count(doc,'w:tbl'),footnotes:count(doc,'w:footnoteReference'),endnotes:count(doc,'w:endnoteReference')};
 const renderedHeadings=paragraphs.filter(p=>/^Heading|^ScriptaBookTitle$/.test(styleOf(p))).length;
 for(const [code,actual,expected] of [['heading-count',renderedHeadings,a.headings.length],['static-toc-count',paragraphs.filter(p=>styleOf(p).startsWith('ScriptaTOC')).length,a.entries.length],['hyperlink-count',metric.hyperlinks,a.links+a.entries.length],['image-count',metric.images,a.images],['table-count',metric.tables,a.tables]])if(actual!==expected)error(code,`Expected ${expected}, found ${actual}.`);
 const names=new Set(all(doc,'w:bookmarkStart').map(n=>n.getAttribute('w:name')));const missing=all(doc,'w:hyperlink').map(n=>n.getAttribute('w:anchor')).filter(n=>n&&!names.has(n));if(missing.length)error('internal-link-target','Internal links target missing bookmarks.',{targets:missing});
 if(Object.keys(files).some(n=>/^word\/header\d*\.xml$/.test(n))||count(doc,'w:headerReference'))error('unexpected-header','Generated headers are forbidden.');
 const pageNums=all(doc,'w:pgNumType'),hasBody=pageNums.some(n=>n.getAttribute('w:fmt')==='decimal');if(hasBody&&pageNums.filter(n=>n.getAttribute('w:fmt')==='decimal'&&n.getAttribute('w:start')==='1').length!==1)error('body-page-number-restarts','Arabic numbering must restart once.');
 let footers=0;for(const [name,data] of Object.entries(files))if(/^word\/footer\d*\.xml$/.test(name)){footers++;const footer=xml(strFromU8(data)),fields=all(footer,'w:instrText').map(n=>n.textContent.trim());if(fields.length!==1||fields[0]!=='PAGE'||all(footer,'w:t').some(n=>n.textContent.trim()&&!/^\d+$/.test(n.textContent.trim())))error('footer-content','Footer must contain one PAGE field.');}if(!footers)error('page-number-field','No footer PAGE field.');
 const noteRefs={footnote:0,endnote:0};for(const ref of a.notes.values())void ref;
 const sourceDoc=(await import('./runtime.mjs')).select;for(const n of sourceDoc.selectAll('a[role=doc-noteref]',a.root)){const note=a.notes.get(n.attribs.href.slice(1));noteRefs[note.kind]++;}
 for(const kind of ['footnote','endnote']){if(metric[`${kind}s`]!==noteRefs[kind])error('note-count',`Incorrect ${kind} reference count.`);if(metric[`${kind}s`]){const part=readXml(files,`word/${kind}s.xml`),ids=new Set(all(part,`w:${kind}`).map(n=>n.getAttribute('w:id')));for(const ref of all(doc,`w:${kind}Reference`))if(!ids.has(ref.getAttribute('w:id')))error('note-target','Missing note target.');if(!all(rels,'Relationship').some(n=>n.getAttribute('Type')===`${R}/${kind}s`))error(`${kind}-relationship`,'Missing note relationship.');}}
 for(const [name,data] of Object.entries(files))if(name.endsWith('.rels')){const parent=name==='_rels/.rels'?'':path.posix.dirname(path.posix.dirname(name));for(const rel of all(xml(strFromU8(data)),'Relationship')){if(rel.getAttribute('TargetMode')==='External')continue;const target=rel.getAttribute('Target'),resolved=target.startsWith('/')?target.slice(1):path.posix.normalize(path.posix.join(parent,target));if(!files[resolved])error('relationship-target',`Missing package target: ${resolved}`);}}
 if(!hasBody)findings.push({severity:'warning',code:'body-boundary-missing',message:'No body boundary was detected; front-matter numbering remains in use.'});
 return {status:findings.some(f=>f.severity==='error')?'failed':findings.length?'passed_with_warnings':'passed',source,artifact:file,findings,metrics:{textCoverage:Number(cov.toFixed(6)),textOrder:Number(order.toFixed(6)),sourceTokens:a.sourceTokens.length,outputTokens:out.length,...metric,visualValidation:false}};
}
export async function convert(source,output,options={}){source=await fs.realpath(source);const target=path.resolve(output||path.join(path.dirname(source),(path.basename(source).toLowerCase()==='index.html'?path.basename(path.dirname(source)):path.basename(source,path.extname(source)))+'.docx'));
 if(!target.toLowerCase().endsWith('.docx'))throw new Error('Output must use the .docx extension.');
 try{await fs.access(target);if(!options.overwrite||!(await owned(target)))throw new Error((await owned(target))?'Use --overwrite for a skill-owned output.':'Refusing to overwrite a DOCX not owned by html2doc-skill.');}catch(err){if(err.code!=='ENOENT')throw err;}
 const model=generate(source,options),m=model.metadata;
 const files=unzipSync(await Packer.toBuffer(new Document({creator:m.author,title:m.title,keywords:'html2doc-skill; Scripta',sections:[{children:[]}]})));
 const put=(name,text)=>{files[name]=strToU8(text);};
 put('word/document.xml',model.document);
 let styleXml=strFromU8(files['word/styles.xml']);
 // Supply Word-native styles with the same book defaults as the source contract.
 const definitions=[['Normal',m.base,false,false],...Array.from({length:6},(_,i)=>[`Heading${i+1}`,[24,18,15,13,12,11][i],true,false]),['ScriptaBookTitle',30,true,false],['ScriptaBookSubtitle',16,false,true],['CodeBlock',9,false,false],['BookQuote',m.base,false,true],...Array.from({length:3},(_,i)=>[`ScriptaTOC${i+1}`,i===2?Math.max(8,m.base-.5):m.base,false,false]),['TOCHeading',18,true,false],['Caption',Math.max(8,m.base-1.5),false,false]];
 const styleDoc=xml(styleXml);for(const [id,size,bold,italic] of definitions){for(const old of all(styleDoc,'w:style').filter(n=>n.getAttribute('w:styleId')===id))old.parentNode.removeChild(old);
 let pp=id==='Normal'?`<w:spacing w:after="${Math.round(m.base*.55*20)}" w:line="300" w:lineRule="auto"/>`:/^Heading/.test(id)?`<w:keepNext/><w:spacing w:before="${Number(id.slice(-1))<=2?360:240}" w:after="120"/><w:outlineLvl w:val="${Number(id.slice(-1))-1}"/>`:id==='ScriptaBookTitle'?'<w:jc w:val="center"/><w:spacing w:before="2400"/>':id==='ScriptaBookSubtitle'?'<w:jc w:val="center"/>':id==='BookQuote'?'<w:ind w:left="576" w:right="576"/>':id.startsWith('ScriptaTOC')?`<w:ind w:left="${(Number(id.slice(-1))-1)*360}"/><w:spacing w:after="${id.endsWith('1')?100:60}"/>`:'';
 const font=id==='CodeBlock'?'Consolas':m.family;
 const styleName = ({ScriptaBookTitle:'Scripta Book Title',ScriptaBookSubtitle:'Scripta Book Subtitle',BookQuote:'Book Quote',CodeBlock:'Code Block',TOCHeading:'TOC Heading'})[id] || id.replace(/^Heading(\d)$/, 'Heading $1').replace(/^ScriptaTOC(\d)$/, 'Scripta TOC $1');
 const node=xml(`<w:style xmlns:w="${W}" w:type="paragraph" w:styleId="${id}"><w:name w:val="${styleName}"/>${id!=='Normal'?'<w:basedOn w:val="Normal"/>':''}<w:pPr>${pp}</w:pPr><w:rPr><w:rFonts w:ascii="${e(font)}" w:hAnsi="${e(font)}" w:eastAsia="${e(font)}"/><w:sz w:val="${Math.round(size*2)}"/>${bold?'<w:b/>':''}${italic?'<w:i/>':''}</w:rPr></w:style>`).documentElement;styleDoc.documentElement.appendChild(styleDoc.importNode(node,true));}
 const { XMLSerializer }=await import('./runtime.mjs');put('word/styles.xml',new XMLSerializer().serializeToString(styleDoc));
 put('word/footer1.xml',`<w:ftr xmlns:w="${W}"><w:p><w:pPr><w:spacing w:after="0" w:line="240" w:lineRule="auto"/><w:jc w:val="center"/></w:pPr><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText xml:space="preserve"> PAGE </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r><w:r><w:t>1</w:t></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p></w:ftr>`);
 const relDoc=readXml(files,'word/_rels/document.xml.rels');let relText=new XMLSerializer().serializeToString(relDoc).replace('</Relationships>',model.relationships.join('')+`<Relationship Id="rScriptaFooter" Type="${R}/footer" Target="footer1.xml"/></Relationships>`);
 let types=strFromU8(files['[Content_Types].xml']).replace('</Types>','<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>');
 for(const [kind,notes] of Object.entries(model.notes))if(notes.length){put(`word/${kind}s.xml`,`<w:${kind}s xmlns:w="${W}">${[-1,0].map((id,i)=>`<w:${kind} w:id="${id}" w:type="${i?'continuationSeparator':'separator'}"><w:p><w:r><w:${i?'continuationSeparator':'separator'}/></w:r></w:p></w:${kind}>`).join('')}${notes.map((t,i)=>`<w:${kind} w:id="${i+1}"><w:p><w:r><w:${kind}Ref/></w:r><w:r><w:t xml:space="preserve"> ${e(t)}</w:t></w:r></w:p></w:${kind}>`).join('')}</w:${kind}s>`);if(!relText.includes(`Type="${R}/${kind}s"`))relText=relText.replace('</Relationships>',`<Relationship Id="rScripta${kind}" Type="${R}/${kind}s" Target="${kind}s.xml"/></Relationships>`);if(!types.includes(`PartName="/word/${kind}s.xml"`))types=types.replace('</Types>',`<Override PartName="/word/${kind}s.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.${kind}s+xml"/></Types>`);}
 put('word/_rels/document.xml.rels',relText);
 for(const {name,data,ext} of model.media){files[`word/media/${name}`]=data;if(!types.includes(`Extension="${ext}"`))types=types.replace('</Types>',`<Default Extension="${ext}" ContentType="image/${{jpg:'jpeg',tif:'tiff'}[ext]||ext}"/></Types>`);}put('[Content_Types].xml',types);
 put('word/numbering.xml',`<w:numbering xmlns:w="${W}">${[1,2].map(num=>`<w:abstractNum w:abstractNumId="${num}">${Array.from({length:9},(_,i)=>`<w:lvl w:ilvl="${i}"><w:start w:val="1"/><w:numFmt w:val="${num===1?'bullet':'decimal'}"/><w:lvlText w:val="${num===1?'•':`%${i+1}.`}"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="${720+i*360}" w:hanging="360"/></w:pPr></w:lvl>`).join('')}</w:abstractNum><w:num w:numId="${num}"><w:abstractNumId w:val="${num}"/></w:num>`).join('')}</w:numbering>`);
 put('word/settings.xml',strFromU8(files['word/settings.xml']).replace('</w:settings>','<w:updateFields w:val="true"/></w:settings>'));
 let core=strFromU8(files['docProps/core.xml']);if(!core.includes('xmlns:dc='))throw new Error('DOCX template lacks metadata namespaces.');core=core.replace('</cp:coreProperties>',`<dc:language>${e(m.language)}</dc:language></cp:coreProperties>`);put('docProps/core.xml',core);
 await fs.mkdir(path.dirname(target),{recursive:true});const temporary=target+'.'+randomUUID()+'.docx';
 try{await fs.writeFile(temporary,zipSync(files,{level:6}),{flag:'wx'});const report=await validate(source,temporary);if(report.status==='failed')throw new Error('Generated DOCX failed validation: '+JSON.stringify(report.findings));await fs.rename(temporary,target);const warnings=[...report.findings.filter(f=>f.severity==='warning'),...model.warnings];return {status:warnings.length?'passed_with_warnings':'passed',artifact:target,warnings,metrics:report.metrics};}finally{await fs.rm(temporary,{force:true});}
}
