import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { randomUUID } from 'node:crypto';
import {run,doctor,requireRuntime,sourceInfo,executable} from './runtime.mjs';
import {qjson,validateReference,limits} from './qa.mjs';
export {doctor};
export function metadata(file){const j=qjson(file),objects=j.qpdf[1],info=objects.trailer.value['/Info'];return typeof info==='string'?objects[`obj:${info}`]?.value||{}:info||{};}
export function exportWord(source,work){const output=path.join(work,'libreoffice-output'),profile=path.join(work,'libreoffice-profile');fs.mkdirSync(output);fs.mkdirSync(profile);fs.writeFileSync(path.join(profile,'registrymodifications.xcu'),'<?xml version="1.0"?><oor:items xmlns:oor="http://openoffice.org/2001/registry"><item oor:path="/org.openoffice.Office.Common/Security/Scripting"><prop oor:name="MacroSecurityLevel" oor:op="fuse"><value>3</value></prop></item></oor:items>');run('soffice',[`-env:UserInstallation=${pathToFileURL(profile).href}`,'--headless','--nologo','--nodefault','--nolockcheck','--norestore','--convert-to','pdf:writer_pdf_Export','--outdir',output,source]);const files=fs.readdirSync(output).filter(f=>/\.pdf$/i.test(f));if(files.length!==1||!fs.statSync(path.join(output,files[0])).size)throw new Error('LibreOffice did not create exactly one non-empty PDF.');return path.join(output,files[0]);}
export function lossless(input,output,profile,work){const j=qjson(input),objs=j.qpdf[1];let ref=objs.trailer.value['/Info'];const changes={};if(typeof ref!=='string'){const max=Math.max(0,...Object.keys(objs).map(k=>Number(k.match(/^obj:(\d+)/)?.[1]||0)));ref=`${max+1} 0 R`;changes.trailer={value:{...objs.trailer.value,'/Info':ref}};}
 changes[`obj:${ref}`]={value:{...(objs[`obj:${ref}`]?.value||{}),'/ScriptaSkill':'u:doc2pdf-skill','/ScriptaProfile':`u:${profile}`,'/Producer':'u:Scripta doc2pdf-skill (LibreOffice + QPDF)','/ModDate':'u:D:'+new Date().toISOString().replace(/[-:T]/g,'').slice(0,14)+'Z'}};
 const update=path.join(work,`metadata-${randomUUID()}.json`);fs.writeFileSync(update,JSON.stringify({qpdf:[{jsonversion:2},changes]}));run('qpdf',[input,`--update-from-json=${update}`,'--linearize','--compress-streams=y','--recompress-flate','--compression-level=9','--object-streams=generate',output],{allowed:[0,3]});run('qpdf',['--check',output],{allowed:[0,3]});}
export function candidate(raw,work,profile){const out=path.join(work,`candidate-${profile}.pdf`);let input=raw;if(profile!=='fidelity'){input=path.join(work,`ghostscript-${profile}.pdf`);const dpi=profile==='balanced'?300:150,quality=profile==='balanced'?92:82;run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.7','-dNOPAUSE','-dBATCH','-dSAFER','-dDetectDuplicateImages=true','-dCompressFonts=true','-dSubsetFonts=true','-dEmbedAllFonts=true','-dPreserveAnnots=true','-dDownsampleColorImages=true','-dDownsampleGrayImages=true','-dColorImageDownsampleType=/Bicubic','-dGrayImageDownsampleType=/Bicubic',`-dColorImageResolution=${dpi}`,`-dGrayImageResolution=${dpi}`,'-dAutoFilterColorImages=false','-dAutoFilterGrayImages=false','-dColorImageFilter=/DCTEncode','-dGrayImageFilter=/DCTEncode',`-dJPEGQ=${quality}`,`-sOutputFile=${input}`,raw]);}lossless(input,out,profile,work);return out;}
function retain(work,output,result){const root=path.join(path.dirname(output),'.doc2pdf-qa');fs.mkdirSync(root,{recursive:true});const dest=path.join(root,`${path.basename(output,'.pdf')}-${randomUUID()}`);fs.writeFileSync(path.join(work,'qa.json'),JSON.stringify(result,null,2));fs.renameSync(work,dest);result.qaArtifacts=dest;}
export function convert(input,output,{profile='fidelity',overwrite=false,keepQaArtifacts=false}={}){if(!(profile in limits))throw new Error('Unknown PDF profile.');const source=sourceInfo(input);requireRuntime(profile);output=path.resolve(output||source.source.replace(/\.[^.]+$/,'.pdf'));if(!/\.pdf$/i.test(output)||output===source.source)throw new Error('Output must be a separate .pdf file.');if(fs.existsSync(output)){if(!overwrite)throw new Error('Use --overwrite for a skill-owned PDF.');if(metadata(output)['/ScriptaSkill']!=='u:doc2pdf-skill')throw new Error('Refusing to overwrite a PDF not owned by doc2pdf-skill.');}
 fs.mkdirSync(path.dirname(output),{recursive:true});const work=fs.mkdtempSync(path.join(path.dirname(output),'.doc2pdf-'));let retained=false;
 try{const raw=exportWord(source.source,work),requested=profile,warnings=[];let file,qa;try{file=candidate(raw,work,profile);qa=validateReference(raw,file,{profile,requestedFonts:source.fonts,sourceLinks:source.links,renderDir:path.join(work,'renders')});}catch(error){if(profile==='fidelity')throw error;qa={status:'failed',findings:[{severity:'error',code:'optimization-failed',message:error.message}]};}if(qa.status==='failed'&&profile!=='fidelity'){warnings.push({severity:'warning',code:'profile-fallback',message:`The ${profile} candidate failed QA; fidelity was published instead.`,details:{failedFindings:qa.findings}});profile='fidelity';file=candidate(raw,work,profile);qa=validateReference(raw,file,{profile,requestedFonts:source.fonts,sourceLinks:source.links,renderDir:path.join(work,'renders')});}if(qa.status==='failed')throw new Error('PDF candidate failed QA: '+JSON.stringify(qa.findings));const rawBytes=fs.statSync(raw).size,outputBytes=fs.statSync(file).size;fs.renameSync(file,output);const result={status:warnings.length||qa.status==='passed_with_warnings'?'passed_with_warnings':'passed',source:source.source,artifact:output,requestedProfile:requested,profile,warnings:[...warnings,...qa.findings.filter(f=>f.severity==='warning')],findings:qa.findings,metrics:{...qa.metrics,rawBytes,outputBytes,savedBytes:rawBytes-outputBytes,sizeRatio:Number((outputBytes/rawBytes).toFixed(6))}};if(keepQaArtifacts){fs.copyFileSync(output,path.join(work,`candidate-${profile}.pdf`));retain(work,output,result);retained=true;}return result;}finally{if(!retained)fs.rmSync(work,{recursive:true,force:true});}}
export function validate(input,pdf,{keepQaArtifacts=false}={}){const source=sourceInfo(input);requireRuntime();pdf=fs.realpathSync(pdf);const stored=metadata(pdf)['/ScriptaProfile']?.replace(/^u:/,''),profile=stored in limits?stored:'fidelity',work=fs.mkdtempSync(path.join(path.dirname(pdf),'.doc2pdf-validate-'));let retained=false;try{const raw=exportWord(source.source,work);const result={...validateReference(raw,pdf,{profile,requestedFonts:source.fonts,sourceLinks:source.links,renderDir:path.join(work,'renders')}),source:source.source,artifact:pdf,profile};if(keepQaArtifacts){retain(work,pdf,result);retained=true;}return result;}finally{if(!retained)fs.rmSync(work,{recursive:true,force:true});}}
export function installCommands(){const missing=['soffice','gs','qpdf'].filter(n=>!executable(n));if(['pdftotext','pdffonts','pdftoppm'].some(n=>!executable(n)))missing.push('pdftoppm');if(!missing.length)return [];if(process.platform==='darwin')return missing.map(n=>n==='soffice'?['brew','install','--cask','libreoffice']:['brew','install',n==='gs'?'ghostscript':n==='pdftoppm'?'poppler':n]);if(process.platform==='linux'){const packages=missing.map(n=>({soffice:'libreoffice-writer',gs:'ghostscript',pdftoppm:'poppler-utils',qpdf:'qpdf'}[n])),prefix=process.getuid?.()===0?[]:['sudo'];if(executable('apt-get'))return [[...prefix,'apt-get','update'],[...prefix,'apt-get','install','-y',...packages]];if(executable('dnf'))return [[...prefix,'dnf','install','-y',...packages.map(n=>n==='poppler-utils'?'poppler-utils':n)]];}throw new Error('Install LibreOffice, QPDF, Poppler and Ghostscript with your platform package manager; see dependencies.md.');}
export function install(yes=false){const commands=installCommands();if(!commands.length)return {status:'already_available',...doctor(),commands:[]};if(!yes)return {status:'cancelled',commands,message:'Review the commands and rerun install-deps --yes to install.'};for(const [cmd,...args] of commands)run(cmd,args,{timeout:1200000});const result=doctor();if(!result.ok)throw new Error('Dependencies remain unavailable after installation.');return {status:'installed',...result,commands};}
