import { checkZip } from './zip.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
const require=createRequire(new URL('../external/runtime/package.json',import.meta.url));
export const {unzipSync,strFromU8}=require('fflate');
const {DOMParser}=require('@xmldom/xmldom');
export const all=(doc,name)=>Array.from(doc.getElementsByTagName(name));
export function xml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw new Error('XML DTDs are unsupported.');return new DOMParser({onError(level,message){throw new Error('Invalid XML: '+message);}}).parseFromString(text,'application/xml');}
export function executable(name){const override=process.env[`SCRIPTA_${name.toUpperCase()}`];if(override){try{fs.accessSync(override,fs.constants.X_OK);return override;}catch{return null;}}const names=name==='soffice'?['soffice','libreoffice']:name==='gs'?['gs','gswin64c']: [name];const dirs=(process.env.PATH||'').split(path.delimiter).filter(Boolean);dirs.push('/opt/homebrew/bin','/usr/local/bin','/Applications/LibreOffice.app/Contents/MacOS');if(process.platform==='win32')dirs.push('C:\\Program Files\\LibreOffice\\program');
 for(const file of [...(override?[override]:[]),...dirs.flatMap(d=>names.map(n=>path.join(d,n+(process.platform==='win32'?'.exe':''))))])try{fs.accessSync(file,fs.constants.X_OK);return file;}catch{}return null;}
export function run(tool,args,{timeout=180000,encoding='utf8',allowed=[0],maxBuffer=256*1024*1024}={}){const command=path.isAbsolute(tool)?tool:executable(tool);if(!command)throw new Error(`Missing ${tool}; run doc2pdf install-deps or see dependencies.md.`);const p=spawnSync(command,args,{encoding,timeout,maxBuffer});if(p.error)throw new Error(`${tool}: ${p.error.message}`);if(p.signal)throw new Error(`${tool} terminated by ${p.signal}.`);if(!allowed.includes(p.status))throw new Error(`${tool} failed (${p.status}): ${p.stderr||p.stdout}`);return p.stdout;}
export function doctor(){const found={};for(const name of ['soffice','qpdf','pdftotext','pdffonts','pdftoppm','gs']){const file=executable(name);let version=null;if(file)try{version=run(file,[['pdfinfo','pdftotext','pdffonts','pdftoppm'].includes(name)?'-v':'--version'],{timeout:10000,allowed:[0]}).trim()||'available';}catch{}found[name]={path:file,version};}const q=found.qpdf.version?.match(/(\d+)\.(\d+)/);const missing=Object.entries(found).filter(([name,v])=>name!=='gs'&&(!v.path||!v.version)).map(([name])=>name);if(!q||(Number(q[1])<11||Number(q[1])===11&&Number(q[2])<4))missing.push('qpdf >=11.4');return {ok:missing.length===0,node:process.versions.node,tools:found,missing};}
export function requireRuntime(profile='fidelity'){const report=doctor();if(!report.ok)throw new Error('Missing runtime dependencies: '+report.missing.join(', '));if(profile!=='fidelity'&&(!report.tools.gs.path||!report.tools.gs.version))throw new Error('The selected profile requires Ghostscript.');return report;}
export function readDocx(file){const bytes=fs.readFileSync(file),files=checkZip(bytes,unzipSync(bytes));if(!files['word/document.xml'])throw new Error('DOCX package is incomplete.');for(const [name,data] of Object.entries(files))if(name.endsWith('.xml')||name.endsWith('.rels'))xml(strFromU8(data));return files;}
export function sourceInfo(file){file=fs.realpathSync(file);const ext=path.extname(file).toLowerCase();if(!['.doc','.docx'].includes(ext))throw new Error('Input must have a .doc or .docx extension.');if(ext==='.doc'){if(!fs.readFileSync(file).subarray(0,8).equals(Buffer.from('D0CF11E0A1B11AE1','hex')))throw new Error('The .doc input is not a valid OLE compound document.');return {source:file,fonts:[],links:null};}
 const files=readDocx(file),fonts=new Set();for(const name of ['word/document.xml','word/styles.xml','word/numbering.xml'])if(files[name])for(const n of all(xml(strFromU8(files[name])),'w:rFonts'))for(const a of ['ascii','hAnsi','eastAsia','cs']){const v=n.getAttribute('w:'+a);if(v&&!v.startsWith('+'))fonts.add(v.trim().replace(/\s+/g,' '));}return {source:file,fonts:[...fonts],links:all(xml(strFromU8(files['word/document.xml'])),'w:hyperlink').length};}
