import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import crypto from 'node:crypto';import {spawnSync} from 'node:child_process';
import '../runtime/shf-core.js';import '../runtime/themes.js';
import {ROOT,inside} from '../scripts/lib/paths.mjs';import {compileFilm,ACTIONS} from '../scripts/lib/director.mjs';import {CATALOG,ASSETS,instantiate,PEOPLE,EMOTIONS} from '../scripts/lib/asset-library.mjs';
import {voiceTasks,attachVoice,audioInfo} from '../scripts/lib/voice.mjs';import {compose,renderWav,MOODS} from '../scripts/lib/music.mjs';import {installPlayer,readFilm,captionsVTT} from '../scripts/shf.mjs';import {analyzeText} from '../scripts/lib/analyze.mjs';import {checkEditorial} from '../scripts/check-editorial.mjs';import {renderSVG} from '../scripts/lib/svg.mjs';
const C=globalThis.SHFCore,json=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p))),clone=x=>structuredClone(x),minimal=()=>compileFilm(json('examples/minimal.direction.json'));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'shf-test-'));process.on('exit',()=>fs.rmSync(tmp,{recursive:true,force:true}));
function mutate(fn){const f=minimal();fn(f);return C.validate(f);}
function wav(ms=1000){const n=Math.round(16000*ms/1000),b=Buffer.alloc(44+n*2);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)b.writeInt16LE(Math.round(1000*Math.sin(i*2*Math.PI*220/16000)),44+i*2);return b;}
test('minimal and custom examples compile without a service',()=>{for(const p of ['minimal','custom-asset'])assert.equal(C.validate(compileFilm(json('examples/'+p+'.direction.json'))).valid,true);});
test('custom IDs remap to instance IDs and do not require arbitrary SVG',()=>{const f=compileFilm(json('examples/custom-asset.direction.json'));let ids=[];C.walk(f.scenes[0].nodes,n=>ids.push(n.id));assert(ids.includes('core.facet'));assert(!ids.some(x=>x.startsWith('$asset')));});
test('502 entries = 16 core +198 recipes +24×12 expressions',()=>{assert.equal(CATALOG.length,502);assert.equal(Object.keys(ASSETS).length,502);assert.equal(new Set(Object.keys(ASSETS)).size,502);assert.equal(PEOPLE.length,24);assert.equal(EMOTIONS.length,12);assert.equal(CATALOG.filter(x=>x.id.startsWith('person-')).length,288);});
for(const meta of CATALOG)test('asset: '+meta.id,()=>{const node=instantiate({id:'item',asset:meta.id,x:600,y:550,scale:1});const f=minimal();f.scenes[0].nodes=[node];f.scenes[0].tracks=[];f.scenes[0].connections=[];assert(C.validate(f).valid,meta.id);for(const theme of ['color','paper','night']){const svg=renderSVG(node,{theme,bounds:meta.bounds});assert(!/NaN|Infinity|\$[A-Za-z]/.test(svg));assert(svg.includes('<svg'));} });
test('same character identity with different expressions changes face data',()=>{assert.notDeepEqual(instantiate({id:'x',asset:'person-02-happy'}),instantiate({id:'x',asset:'person-02-sad'}));});
test('semantic vocabulary remains bounded',()=>assert.equal(ACTIONS.length,24));
test('unknown action rejected',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].actions[0].action='arbitrary.eval';assert.throws(()=>compileFilm(d),/Unsupported/);});
test('wrong rig action rejected',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].actions[0].actor='mira';assert.throws(()=>compileFilm(d),/requires book/);});
test('missing anchor rejected',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].connections=[{id:'link',from:{node:'mira',anchor:'absent'},to:{node:'book',anchor:'left'}}];assert.throws(()=>compileFilm(d),/anchor/);});
test('cue uses actual beat position',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].beats[0].id='b1';d.scenes[0].actions[0].cue={beatId:'b1',edge:'start',offsetMs:80};const f=compileFilm(d);assert.equal(f.scenes[0].direction.actions[0].atMs,580);});
test('missing cue rejected',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].actions[0].cue={beatId:'none'};assert.throws(()=>compileFilm(d),/Unknown cue/);});
test('state is seek-order-independent',()=>{const s=minimal().scenes[0],a=C.stateAt(s,8500);C.stateAt(s,13000);assert.deepEqual(C.stateAt(s,8500),a);});
test('scene boundary selects next scene exactly',()=>{const f=minimal();f.scenes.push({...clone(f.scenes[0]),id:'second'});assert.equal(C.sceneAt(f,15000).index,1);assert.equal(C.sceneAt(f,14999).index,0);assert.equal(C.sceneAt(f,30000).localMs,15000);});
test('key easing endpoints exact',()=>{for(const name of ['linear','inOut','out','hold'])assert.equal(C.sample([{t:0,v:0},{t:100,v:1,ease:name}],100),1);});
for(const [name,fn]of Object.entries({script:f=>f.scenes[0].nodes[0].type='script',event:f=>f.scenes[0].nodes[0].attrs.onclick='alert(1)',url:f=>f.scenes[0].nodes[0].attrs.fill='url(http://bad)',nan:f=>f.scenes[0].durationMs=NaN,filename:f=>f.id='../escape',badSource:f=>f.scenes[0].beats[0].sourceRefs=['missing'],badSpoken:f=>f.scenes[0].beats[0].spokenEndMs=90000,captionOverlap:f=>f.scenes[0].captions=[{startMs:0,endMs:1000,text:'a'},{startMs:500,endMs:1100,text:'b'}],musicTooLoud:f=>f.soundtrack={gain:.5},totalMismatch:f=>f.durationMs=1,duplicateScene:f=>f.scenes.push(clone(f.scenes[0])),unknownTrack:f=>f.scenes[0].tracks.push({target:'not-there',property:'x',keys:[{t:0,v:0}]})}))test('rejects '+name,()=>assert.equal(mutate(fn).valid,false));
test('malformed inputs return invalid rather than throw',()=>{for(const f of [null,{},[],{...minimal(),sources:'bad'},{...minimal(),scenes:[null]}])assert.equal(C.validate(f).valid,false);});
test('archive round trip retains nodes and metadata',async()=>{const f=minimal(),read=await C.loadFile(new Blob([C.packFilm(f)]));assert.deepEqual(read,f);});
test('archive CRC rejects changed bytes',async()=>{const z=C.packFilm(minimal());z[60]^=1;await assert.rejects(C.unzip(z));});
test('archive traversal rejected at writer',()=>assert.throws(()=>C.zipStore({'../x':'bad'}),/Unsafe/));
test('archive unsupported bytes fail',async()=>await assert.rejects(C.unzip(new Uint8Array(30))));
test('offline movie missing bytes fails packing',()=>{const f=minimal();f.assets={x:{mime:'audio/wav',path:'assets/x.wav'}};assert.throws(()=>C.packFilm(f),/missing audio/);});
test('clip overlap and scene overrun rejected',()=>{const f=minimal();f.assets={a:{mime:'audio/wav',data:Buffer.from(wav()).toString('base64')}};f.scenes[0].audioClips=[{assetId:'a',startMs:0,durationMs:1000},{assetId:'a',startMs:500,durationMs:1000}];assert(!C.validate(f).valid);f.scenes[0].audioClips[1].startMs=14900;assert(!C.validate(f).valid);});
test('voice tasks contain every line and separate performance metadata',()=>{const d=json('examples/minimal.direction.json'),t=voiceTasks(d);assert.equal(t.tasks.length,2);assert(t.tasks[0].performance.avoid.includes('reading stage directions'));assert(d.scenes[0].beats[0].id);assert.equal(t.tasks[0].text,d.scenes[0].beats[0].text);});
test('native WAV measurement is exact',()=>{const p=path.join(tmp,'1.wav');fs.writeFileSync(p,wav(1337));assert.equal(audioInfo(p).durationMs,1337);});
function voiceFixture(){const d=json('examples/minimal.direction.json'),tasks=voiceTasks(d);const receipts={provider:'test-oscillator-not-speech',lines:tasks.tasks.map((t,i)=>{const file=t.id+'.wav';fs.writeFileSync(path.join(tmp,file),wav(i?1800:900));return {id:t.id,file,quality:'test-fixture'};})};return{d,receipts};}
test('line audio retimes beats, actions, total and packs',()=>{const {d,receipts}=voiceFixture(),out=attachVoice(d,receipts,tmp);assert.equal(out.report.length,2);assert.equal(out.direction.scenes[0].audioClips.length,2);assert(out.direction.durationMs<15000);assert(C.validate(compileFilm(out.direction)).valid);});
test('longer narration extends scene rather than truncating it',()=>{const {d,receipts}=voiceFixture();fs.writeFileSync(path.join(tmp,receipts.lines[0].file),wav(18000));const out=attachVoice(d,receipts,tmp);assert(out.direction.durationMs>18000);assert(C.validate(compileFilm(out.direction)).valid);});
test('missing receipt fails',()=>{const {d,receipts}=voiceFixture();receipts.lines.pop();assert.throws(()=>attachVoice(d,receipts,tmp),/Missing voice/);});
test('duplicate receipt fails',()=>{const {d,receipts}=voiceFixture();receipts.lines.push(receipts.lines[0]);assert.throws(()=>attachVoice(d,receipts,tmp),/Duplicate/);});
test('wrong audio hash fails',()=>{const {d,receipts}=voiceFixture();receipts.lines[0].sha256='wrong';assert.throws(()=>attachVoice(d,receipts,tmp),/hash mismatch/);});
test('path escape fails',()=>assert.throws(()=>inside(tmp,'../outside.wav'),/escapes/));
test('symlink escape fails',()=>{const out=fs.mkdtempSync(path.join(os.tmpdir(),'shf-outside-'));try{fs.symlinkSync(out,path.join(tmp,'link'),'dir');assert.throws(()=>inside(tmp,'link/audio.wav'),/Symlink/);}finally{fs.rmSync(out,{recursive:true,force:true});}});
for(const mood of Object.keys(MOODS))test('original cue: '+mood,()=>{const score=compose(mood,4),{bytes,metrics}=renderWav(score);assert.equal(metrics.durationSeconds,4);assert(metrics.rms>0);assert.equal(bytes.toString('ascii',0,4),'RIFF');assert.deepEqual(renderWav(score).bytes,bytes);});
test('music rejects invalid velocity, time and duration',()=>{for(const [key,value]of [['velocity',NaN],['time',-1],['duration',999]]){const s=compose('calm',4);s.events[0][key]=value;assert.throws(()=>renderWav(s));}assert.throws(()=>compose('calm',NaN));});
test('editorial span/hash example passes exact text checks',()=>assert(checkEditorial(json('assets/templates/editorial.example.json'),fs.readFileSync(path.join(ROOT,'assets/templates/source.example.txt'),'utf8')).valid));
test('editorial cannot invent quote or field novelty',()=>{const source=fs.readFileSync(path.join(ROOT,'assets/templates/source.example.txt'),'utf8'),p=json('assets/templates/editorial.example.json');p.claims[0].spans[0].quote='fake';assert(!checkEditorial(p,source).valid);p.claims[0].noveltyScope='externally-verified';assert(checkEditorial(p,source).errors.some(e=>e.includes('novelty')));});
test('analyzer is explicit about extractive draft and preserves source hash',()=>{const source='Libertatea cere reflecție. O ușă deschisă nu dovedește autonomia. Acest exemplu este o interpretare.';const a=analyzeText(source,{language:'ro',targetMinutes:7,genre:'philosophy'});assert(JSON.stringify(a).includes(crypto.createHash('sha256').update(source).digest('hex')));assert(JSON.stringify(a).includes('Libertatea'));});
test('player installer works in unrelated path with spaces, refuses overwrite',()=>{const dest=path.join(tmp,'unrelated project','public','shf');const a=installPlayer(dest);assert(fs.existsSync(path.join(dest,'shf-player.js')));assert.equal(installPlayer(dest).runtimeSha256,a.runtimeSha256);fs.appendFileSync(path.join(dest,'shf-player.js'),'CUSTOM');assert.throws(()=>installPlayer(dest),/Refusing to overwrite/);});
test('player contains no viewer feedback or notes controls',()=>{const s=fs.readFileSync(path.join(ROOT,'runtime/shf-player.js'),'utf8');assert(!/id=["'](?:note|feedback|saveNote|noteText)/.test(s));assert(!/localStorage\.(?:getItem|setItem)\(['"](?!shf-caption-scale['"])/.test(s));});
test('skill entry includes complete relative dependencies',()=>{const s=fs.readFileSync(path.join(ROOT,'SKILL.md'),'utf8');assert(s.startsWith('---\nname: shf-presentation-creator\n'));assert(s.split('\n').length<500);for(const m of s.matchAll(/\]\((references\/[^)]+)\)/g))assert(fs.existsSync(path.join(ROOT,m[1])));});
for(const name of ['visual-lab','mars-library','freedom-practice','governable-ai'])test('bundled film round trip: '+name,async()=>{const f=await readFilm(path.join(ROOT,'examples/rendered',name+'.shf'));assert(C.validate(f).valid);assert(f.scenes.every(s=>s.audioClips.length===s.beats.length));assert(captionsVTT(f).startsWith('WEBVTT'));});
test('CLI catalog queries actual library',()=>{const r=spawnSync(process.execPath,[path.join(ROOT,'scripts/shf.mjs'),'catalog','microscope'],{encoding:'utf8'});assert.equal(r.status,0);assert(JSON.parse(r.stdout).some(x=>x.id==='microscope'));});

test('repeated moves preserve previous endpoint without snap',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].actions=[{actor:'mira',action:'moveTo',x:450,atMs:1000,durationMs:1000},{actor:'mira',action:'moveTo',x:550,atMs:4000,durationMs:1000}];const f=compileFilm(d),s=f.scenes[0];assert.equal(C.stateAt(s,4000).get('mira').x,450);assert.equal(C.stateAt(s,5000).get('mira').x,550);});
test('compiler does not mutate a cue action supplied by the author',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].beats[0].id='b';d.scenes[0].actions[0].cue={beatId:'b',edge:'start'};const before=structuredClone(d);compileFilm(d);assert.deepEqual(d,before);});
test('voice discovery finds an actual allowed skill without claiming availability',()=>{const dir=path.join(tmp,'skills','sample-voice');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'SKILL.md'),'---\nname: sample-voice\ndescription: text-to-speech narration and pronunciation\n---\nUse a real provider.');const p=spawnSync(process.execPath,[path.join(ROOT,'scripts/discover-skills.mjs'),path.join(tmp,'skills')],{encoding:'utf8'});assert.equal(p.status,0);const d=JSON.parse(p.stdout);assert(d.candidates.some(x=>x.name==='sample-voice'&&x.status==='candidate-needs-capability-verification'));});
test('voice discovery without roots asks for host discovery',()=>{const p=spawnSync(process.execPath,[path.join(ROOT,'scripts/discover-skills.mjs')],{encoding:'utf8',env:{...process.env,SHF_SKILL_ROOTS:''}});assert.equal(JSON.parse(p.stdout).status,'host-discovery-required');});

test('narration tasks reject multiple sentences in one beat',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].beats[0].text='One sentence. Another sentence.';assert.throws(()=>voiceTasks(d),/one sentence/);d.scenes[0].beats[0].text='One sentence with an explicit, bounded conclusion.';assert.equal(voiceTasks(d).tasks.length,2);});
test('sentence segmentation preserves technical acronyms and decimal numbers',()=>{assert.deepEqual(C.splitSentences('An AI Agent uses MCP tools at version 2.5. The Robot retains its identity.'),['An AI Agent uses MCP tools at version 2.5.','The Robot retains its identity.']);});
test('edited narration invalidates its voice receipt',()=>{const {d,receipts}=voiceFixture();receipts.lines[0].textSha256=crypto.createHash('sha256').update(d.scenes[0].beats[0].text).digest('hex');d.scenes[0].beats[0].text='A different sentence changes the recording.';assert.throws(()=>attachVoice(d,receipts,tmp),/Narration text changed/);});
test('CLI runs through a symlinked skill folder',()=>{const link=path.join(tmp,'linked skill');fs.symlinkSync(ROOT,link,'dir');const r=spawnSync(process.execPath,[path.join(link,'scripts/shf.mjs'),'catalog','microscope'],{encoding:'utf8'});assert.equal(r.status,0);assert(JSON.parse(r.stdout).some(x=>x.id==='microscope'));});
test('source analysis defaults to English and a semantic why-how-what review',()=>{const a=analyzeText('A persistent virtual worker retains project history while its reasoning software changes.');assert.equal(a.language,'en');assert.deepEqual(a.narrativeFramework.order,['why','how','what']);assert.match(a.narrationStandard,/one sentence/);});

test('dynamic expressions preserve identity and switch to a distinct face',()=>{const d=json('examples/minimal.direction.json');const actor=d.scenes[0].objects.find(o=>o.id==='mira');actor.asset='person-02-curious';actor.options={dynamicExpressions:true};d.scenes[0].actions=[{actor:'mira',action:'character.express',emotion:'worried',atMs:1000,durationMs:500},{actor:'mira',action:'character.express',emotion:'relieved',atMs:3000,durationMs:500}];const f=compileFilm(d),s=f.scenes[0];assert(C.validate(f).valid);assert.equal(C.stateAt(s,2000).get('mira.expression.worried').opacity,1);assert.equal(C.stateAt(s,4000).get('mira.expression.worried').opacity,0);assert.equal(C.stateAt(s,4000).get('mira.expression.relieved').opacity,1);assert.deepEqual(C.stateAt(s,2000),C.stateAt(s,2000));});
test('expressive gestures settle and respect reduced motion',()=>{const d=json('examples/minimal.direction.json');d.scenes[0].actions=[{actor:'mira',action:'character.gesture',gesture:'question',atMs:1000,durationMs:2000}];const f=compileFilm(d),s=f.scenes[0];assert(C.validate(f).valid);assert.notEqual(C.stateAt(s,2100).get('mira.armR').rotate,0);assert.equal(C.stateAt(s,3100).get('mira.armR').rotate,0);assert.equal(C.stateAt(s,2100,true).get('mira.armR').rotate,0);});

test('default and studio themes contain no decorative background geometry',()=>{for(const setting of [undefined,'minimal','studio']){const d=json('examples/minimal.direction.json');d.scenes[0].setting=setting;const f=compileFilm(d);for(const theme of ['color','paper','night']){assert(!f.scenes[0].nodes.some(n=>n.id.startsWith('set.')),theme);assert(C.validate(f).valid);}}});

test('book introduction needs a reading contract beyond a valid technical explanation',()=>{
 const source=fs.readFileSync(path.join(ROOT,'assets/templates/source.example.txt'),'utf8'),p=json('assets/templates/editorial.example.json');
 assert(checkEditorial(p,source).valid);p.purpose='book-introduction';assert(!checkEditorial(p,source).valid);
 p.readerInvitation={reasonToExist:'Separate visible execution from evidence.',readerPromise:'A vocabulary for judging claims.',audienceFit:'Readers evaluating AI results.',closingInvitation:'Begin with the evidence discussion.',readerOutcomes:['Distinguish trace from proof.'],bookJourney:['Question, distinction, conditions.'],contentSamples:[{sceneId:'mechanism',readingValue:'One concrete distinction.'}],reservedForReading:['The fuller argument.']};
 for(const scene of p.scenePlan)scene.lens='book';assert(checkEditorial(p,source).valid);
 p.readerInvitation.contentSamples[0].sceneId='missing';assert(!checkEditorial(p,source).valid);
});

test('explicit custom character rigs can perform gestures, incomplete rigs are rejected',()=>{
 const d=json('examples/minimal.direction.json');const scene=d.scenes[0];
 const visual=instantiate({id:'$asset',asset:'person-02-curious',options:{dynamicExpressions:true}});
 scene.objects=[{id:'mascot',asset:'custom',visual,options:{rig:'character'}}];scene.connections=[];scene.actions=[{actor:'mascot',action:'character.gesture',gesture:'invite',atMs:100,durationMs:1000},{actor:'mascot',action:'character.express',emotion:'happy',atMs:1500,durationMs:300}];d.scenes=[scene];
 assert(C.validate(compileFilm(d)).valid);
 delete scene.objects[0].options.rig;assert.throws(()=>compileFilm(d),/requires character/);
});

test('voice attachment preserves real thinking time and explicit pauses',()=>{const {d,receipts}=voiceFixture();d.scenes[0].beats[0].performance={pauseAfterMs:1400};const out=attachVoice(d,receipts,tmp).direction.scenes[0];assert.equal(out.beats[0].endMs-out.beats[0].spokenEndMs,1400);assert(out.audioClips[1].startMs-(out.audioClips[0].startMs+out.audioClips[0].durationMs)>=1400);assert(out.beats[1].endMs-out.beats[1].spokenEndMs>=1000);});
