import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {ROOT,canonical,hash,parseArgs,safeRelative,readJSON,writeJSON} from '../src/util.mjs';
import {encodeWav,decodeWav,resample,statistics,envelope,mono} from '../src/wav.mjs';
import {validateScore} from '../src/schema.mjs';
import {compileTimeline} from '../src/timeline.mjs';
import {mixScene,duckAt,synthesizePreset,roomReflections} from '../src/dsp.mjs';
import {draftScore} from '../src/draft.mjs';
import {actingInstruction} from '../src/backend.mjs';
const schema=await readJSON(path.join(ROOT,'schemas/score.schema.json'));
const minimal=await readJSON(path.join(ROOT,'examples/minimal.score.json'));
const clone=x=>structuredClone(x);
const signal=(n=2400,sr=24000,value=.2)=>({sampleRate:sr,channels:[Float32Array.from({length:n},()=>value)]});
const p=(frames=24000,sha256='a'.repeat(64))=>({frames,audibleFrames:frames,asset:'a',dryAsset:'dry',selectedTake:0,sha256,envelope:{hopFrames:960,values:[1]}});

test('canonical keys have a stable order',()=>assert.equal(hash(canonical({b:2,a:1})),hash(canonical({a:1,b:2}))));
test('CLI rejects duplicate options',()=>assert.throws(()=>parseArgs(['--out','a','--out','b']),/Duplicate/));
test('CLI parses explicit boolean flags',()=>assert.deepEqual(parseArgs(['render','a','--allow-degraded','--out','b']),{positional:['render','a'],options:{'allow-degraded':true,out:'b'}}));
test('relative paths cannot escape a playback bundle',()=>assert.throws(()=>safeRelative('/a/b','../bad'),/escapes/));
test('WAV mono PCM16 round trip preserves frame count and precision',()=>{const a=signal();const b=decodeWav(encodeWav(a));assert.equal(b.frames,2400);assert.equal(b.sampleRate,24000);assert.ok(Math.abs(b.channels[0][42]-.2)<1/32768);});
test('WAV stereo does not accidentally swap channels',()=>{const a={sampleRate:24000,channels:[new Float32Array([.2,.4]),new Float32Array([-.4,-.2])]};const b=decodeWav(encodeWav(a));assert.ok(b.channels[0][0]>0);assert.ok(b.channels[1][0]<0);assert.equal(b.frames,2);});
test('WAV truncation is rejected',()=>assert.throws(()=>decodeWav(encodeWav(signal()).subarray(0,100)),/Truncated/));
test('Non-finite PCM input is rejected',()=>{const a=signal();a.channels[0][7]=NaN;assert.throws(()=>encodeWav(a),/non-finite/);});
test('Mismatched stereo channel sizes are rejected',()=>assert.throws(()=>encodeWav({sampleRate:24000,channels:[new Float32Array(4),new Float32Array(2)]}),/Mismatched/));
test('WAV parser skips unknown padded chunks',()=>{const original=encodeWav(signal(20));const extra=Buffer.alloc(10);extra.write('JUNK');extra.writeUInt32LE(1,4);extra[8]=37;const b=Buffer.concat([original.subarray(0,12),extra,original.subarray(12)]);b.writeUInt32LE(b.length-8,4);assert.equal(decodeWav(b).frames,20);});
test('Stereo-to-mono average is explicit',()=>{const a={sampleRate:24000,channels:[new Float32Array([.5]),new Float32Array([-.5])]};assert.equal(mono(a).channels[0][0],0);});
test('Resampling preserves exact duration on integral ratios',()=>{const b=resample(signal(22050,22050),24000);assert.equal(b.channels[0].length,24000);assert.equal(b.sampleRate,24000);});
test('Windowed-sinc resampler preserves DC',()=>{const b=resample(signal(1000,22050),24000);assert.ok(b.channels[0].every(x=>Math.abs(x-.2)<1e-6));});
test('Downsampling attenuates a frequency above the output Nyquist limit',()=>{const a={sampleRate:48000,channels:[Float32Array.from({length:4800},(_,i)=>.3*Math.sin(2*Math.PI*18000*i/48000))]};const b=resample(a,24000);assert.ok(statistics(b).rms<.02);});
test('Amplitude envelopes are explicitly not phoneme alignment',()=>{const e=envelope(signal());assert.equal(e.kind,'amplitude-not-phonemes');assert.ok(e.values.every(x=>x>=0&&x<=1));});
test('Minimal score validates',()=>assert.equal(validateScore(clone(minimal),schema).id,'hello'));
test('Unknown score properties are rejected instead of ignored',()=>{const s=clone(minimal);s.perfectEmotion=true;assert.throws(()=>validateScore(s,schema),/unknown field/);});
test('Unknown voice is rejected',()=>{const s=clone(minimal);s.beats[0].speaker='unknown';assert.throws(()=>validateScore(s,schema),/Unknown speaker/);});
test('Duplicate IDs are rejected',()=>{const s=clone(minimal);s.beats[1].id=s.beats[0].id;assert.throws(()=>validateScore(s,schema),/Duplicate/);});
test('Emotion intensity is bounded',()=>{const s=clone(minimal);s.beats[0].direction.intensity=1.01;assert.throws(()=>validateScore(s,schema),/range/);});
test('Selected take uses a checked zero-based index',()=>{const s=clone(minimal);s.beats[0].selectedTake=1;assert.throws(()=>validateScore(s,schema),/selectedTake/);});
test('Source spans must match exact spoken text',()=>{const s=clone(minimal);s.sourceText='other words';s.beats[0].sourceSpan={start:0,end:5};assert.throws(()=>validateScore(s,schema),/sourceSpan/);});
test('Source spans use JavaScript UTF-16 indices, including emoji',()=>{const s=clone(minimal);s.sourceText='🌗 Hello.';s.beats[0].text='Hello.';s.beats[0].sourceSpan={start:3,end:9};validateScore(s,schema);});
test('Timing cycles are caught before synthesis',()=>{const s=clone(minimal);s.beats[0].at={beat:'end',edge:'end'};assert.throws(()=>validateScore(s,schema),/cycle/);});
test('Unknown anchors are rejected',()=>{const s=clone(minimal);s.visuals[0].at={beat:'missing',edge:'end'};assert.throws(()=>validateScore(s,schema),/unknown beat/);});
test('Procedural effects require a duration',()=>{const s=clone(minimal);s.effects=[{id:'boom',preset:'metal'}];assert.throws(()=>validateScore(s,schema),/requires seconds/);});
test('External assets cannot also specify a procedural preset',()=>{const s=clone(minimal);s.effects=[{id:'boom',preset:'metal',file:'a.wav',seconds:1}];assert.throws(()=>validateScore(s,schema),/exactly one/);});
test('Pause duration belongs to the scene, not to speech frames',()=>{const t=compileTimeline(minimal,{hello:p(24000),end:p(12000)});assert.equal(t.events[0].endFrame,24000);assert.equal(t.events[1].endFrame-t.events[1].startFrame,28800);assert.equal(t.events[2].startFrame,52800);assert.equal(t.events[2].endFrame,64800);});
test('Changing one speech duration shifts dependent visuals exactly',()=>{const a=compileTimeline(minimal,{hello:p(24000),end:p(12000)}),b=compileTimeline(minimal,{hello:p(24777),end:p(12000)});assert.equal(b.visuals[0].startFrame-a.visuals[0].startFrame,777);});
test('Absolute anchors stay absolute when preceding audio changes',()=>{const s=clone(minimal);s.beats[2].at=4;const a=compileTimeline(s,{hello:p(24000),end:p(12000)}),b=compileTimeline(s,{hello:p(30000),end:p(12000)});assert.equal(a.events[2].startFrame,b.events[2].startFrame);});
test('Forward anchors work when they are acyclic',()=>{const s=clone(minimal);s.beats[0].at={beat:'end',edge:'end',offsetSeconds:.1};s.beats[2].at=0;const t=compileTimeline(s,{hello:p(24000),end:p(12000)});assert.equal(t.events[0].startFrame,14400);});
test('Negative resolved start times are rejected',()=>{const s=clone(minimal);s.beats[2].at={beat:'hello',edge:'start',offsetSeconds:-1};assert.throws(()=>compileTimeline(s,{hello:p(),end:p()}),/before scene zero/);});
test('Reverb tails do not move the semantic speech-end anchor',()=>{const a=p(24000);a.audibleFrames=30000;const t=compileTimeline(minimal,{hello:a,end:p()});assert.equal(t.events[0].endFrame,24000);assert.equal(t.events[0].audibleEndFrame,30000);assert.equal(t.events[1].startFrame,24000);});
test('Verified markers resolve to frame-accurate anchors',()=>{const s=clone(minimal);s.beats[0].markers=[{id:'word',seconds:.25,basis:'manual',audioSha256:'a'.repeat(64)}];s.visuals[0].at={beat:'hello',edge:'marker',marker:'word',offsetSeconds:.1};const t=compileTimeline(s,{hello:p(),end:p()});assert.equal(t.visuals[0].startFrame,8400);});
test('Markers from a different audio file are rejected',()=>{const s=clone(minimal);s.beats[0].markers=[{id:'word',seconds:.25,basis:'manual',audioSha256:'b'.repeat(64)}];assert.throws(()=>compileTimeline(s,{hello:p(),end:p()}),/Stale marker/);});
test('Markers cannot point past the dry clip end',()=>{const s=clone(minimal);s.beats[0].markers=[{id:'word',seconds:3,basis:'manual',audioSha256:'a'.repeat(64)}];assert.throws(()=>compileTimeline(s,{hello:p(),end:p()}),/outside/);});
test('Sound presets are deterministic for a fixed seed',()=>assert.deepEqual(synthesizePreset('rain',1,24000,7),synthesizePreset('rain',1,24000,7)));
test('Noise seeds alter procedural ambience',()=>assert.notDeepEqual(synthesizePreset('rain',.1,24000,7),synthesizePreset('rain',.1,24000,8)));
test('All sound presets have finite samples and exact lengths',()=>{for(const x of ['space-hum','wind','rain','drone','metal','chime','airlock','pulse']){const s=statistics(synthesizePreset(x,.2));assert.equal(s.frames,4800);assert.ok(s.peak<1);}});
test('Loop edges are tapered to avoid discontinuities',()=>{const a=synthesizePreset('rain',1).channels[0];assert.equal(Math.abs(a[0]),0);assert.equal(Math.abs(a.at(-1)),0);});
test('Dry input remains unmodified by the room processor',()=>{const a=signal();const b=roomReflections(a,{wet:0});b.channels[0][0]=0;assert.notEqual(a.channels[0][0],0);});
test('Room reflections preserve the initial voice and add an explicit tail',()=>{const a=signal(2400);const b=roomReflections(a,{wet:.1,delayMs:50});assert.ok(b.channels[0].length>a.channels[0].length);assert.equal(a.channels[0][0],b.channels[0][0]);});
test('Ducking recovers to unity outside speech',()=>{assert.equal(duckAt(0,[[24000,48000]],24000,-12),1);assert.ok(duckAt(30000,[[24000,48000]],24000,-12)<.3);assert.equal(duckAt(72000,[[24000,48000]],24000,-12),1);});
test('Overlap ducking takes the maximum activation, not stacked attenuation',()=>assert.equal(duckAt(30000,[[24000,48000]],24000,-12),duckAt(30000,[[24000,48000],[25000,45000]],24000,-12)));
function mixTimeline(events,beds=[],n=2400){return {sampleRate:24000,durationFrames:n,events,beds,ceilingDbFS:-1};}
test('Hard-left panning does not leak into the right channel',()=>{const t=mixTimeline([{kind:'speech',asset:'a',startFrame:0,endFrame:2400,gainDb:0,pan:-1}]);const m=mixScene(t,{a:signal()});assert.ok(m.audio.channels[1].every(v=>Math.abs(v)<1e-7));});
test('Scene silence is truly empty when no bed is present',()=>{const t=mixTimeline([{kind:'speech',asset:'a',startFrame:1200,endFrame:2400,gainDb:0,pan:0}]);const m=mixScene(t,{a:signal(1200)});assert.ok(m.audio.channels[0].slice(0,1200).every(x=>x===0));});
test('Sample-peak ceiling is enforced for overlapping voices',()=>{const t=mixTimeline([1,2,3].map(()=>({kind:'speech',asset:'a',startFrame:0,endFrame:2400,gainDb:6,pan:0})));const m=mixScene(t,{a:signal(2400,24000,.8)});assert.ok(m.masterGain<1);assert.ok(m.statistics.peak<=10**(-1/20)+1e-6);});
test('Drafting preserves source text without inventing dialogue',()=>{const text='First sentence.\nSecond sentence? Yes!';const d=draftScore(text);validateScore(d,schema);assert.equal(d.beats.map(b=>b.text).join(' '), 'First sentence. Second sentence? Yes!');assert.equal(d.sourceText,text);});
test('Empty input is rejected by the draft command',()=>assert.throws(()=>draftScore('   '),/No text/));
test('Acting instruction includes emotion and does not change source text',()=>{const d={emotion:'restrained fear',intensity:.6,pace:.8,emphasis:['door']};const instruction=actingInstruction(d);assert.ok(instruction.includes('restrained fear'));assert.ok(instruction.includes('door'));assert.ok(instruction.includes('slowly'));});
