#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';
import {CATALOG,instantiate} from './lib/asset-library.mjs';import {ROOT} from './lib/paths.mjs';import {renderSVG} from './lib/svg.mjs';
const dir=path.join(ROOT,'assets/library');fs.mkdirSync(path.join(dir,'svg'),{recursive:true});
const records=CATALOG.map(meta=>{
 const node=instantiate({id:meta.id,asset:meta.id,x:0,y:0,scale:1});
 const svg=renderSVG(node,{bounds:meta.bounds});fs.writeFileSync(path.join(dir,'svg',meta.id+'.svg'),svg);
 return {...meta,node};
});
fs.writeFileSync(path.join(dir,'catalog.json'),JSON.stringify(CATALOG,null,2));
const renderCode=renderSVG.toString();const themes=JSON.stringify(globalThis.SHFThemes);
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SHF Asset Library</title><style>
*{box-sizing:border-box}body{margin:0;padding:24px;background:#f3f5f4;color:#233d49;font:14px/1.5 system-ui}main{max-width:1200px;margin:auto}h1{font:36px Georgia;margin:4px 0 10px}.kicker{font-size:10px;letter-spacing:.22em;color:#6d8690}.toolbar{display:flex;gap:10px;flex-wrap:wrap;position:sticky;top:0;z-index:2;background:#f3f5f4ed;padding:12px 0}input,select,button{font:inherit;border:1px solid #c6d4d9;border-radius:8px;padding:10px;background:white;color:#233d49}input{flex:1;min-width:170px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:14px}.card{border-radius:14px;overflow:hidden;border:1px solid #d8e0e2;background:#fff}.art{height:184px;padding:13px}.art svg{height:100%;width:100%;display:block}.card h3{font-size:12px;margin:0 11px 3px}.card p{font:10px ui-monospace,monospace;color:#6a8390;margin:0 11px 9px;word-break:break-all}.card button{font-size:10px;margin:0 11px 11px;padding:5px 8px;cursor:pointer}.footer{display:flex;justify-content:space-between;margin:20px 0;align-items:center}#stats{color:#607e89;font-size:12px}.hint{max-width:940px;color:#597581;font-size:13px}@media(max-width:540px){body{padding:14px}.grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.art{height:168px;padding:9px}h1{font-size:28px}.toolbar{gap:6px}.toolbar select{max-width:145px}}
</style><main><div class="kicker">SCRIPTAHUB FILM · REUSABLE VISUAL REPERTORY</div><h1>Familiar characters. New stories.</h1><p class="hint">502 entries: 214 core/object types and 24 character identities × 12 expressions. Character variants are not counted as new object silhouettes. Search names, concepts or emotions. All assets are original vector constructions; the supplied SVGs use the Color palette.</p><div class="toolbar"><input id="query" placeholder="Search: microscope, happy, curious…" aria-label="Search assets"><select id="category"><option value="">All categories</option></select><select id="theme"><option value="color">Color</option><option value="paper">Light gallery</option><option value="night">Dark theatre</option></select></div><p id="stats"></p><div id="grid" class="grid"></div><div class="footer"><button id="prev">Previous</button><span id="page"></span><button id="next">Next</button></div></main><script>
const data=${JSON.stringify(records).replace(/</g,'\\u003c')};globalThis.SHFThemes=${themes};const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const renderSVG=${renderCode};let page=0,limit=36;
const $=id=>document.getElementById(id);for(const c of [...new Set(data.map(a=>a.category))]){const o=document.createElement('option');o.value=c;o.textContent=c;$('category').append(o);}
function render(){const q=$('query').value.toLowerCase(),cat=$('category').value,theme=$('theme').value,list=data.filter(a=>(!cat||a.category===cat)&&[a.id,a.label,...a.tags].join(' ').toLowerCase().includes(q));page=Math.max(0,Math.min(page,Math.ceil(list.length/limit)-1));$('grid').replaceChildren();for(const a of list.slice(page*limit,(page+1)*limit)){const card=document.createElement('article');card.className='card';const art=document.createElement('div');art.className='art';art.style.background=SHFThemes[theme].bg;art.innerHTML=renderSVG(a.node,{theme,bounds:a.bounds});const h=document.createElement('h3');h.textContent=a.label;const p=document.createElement('p');p.textContent=a.id;const b=document.createElement('button');b.textContent='SVG';b.onclick=()=>{const u=URL.createObjectURL(new Blob([renderSVG(a.node,{theme,bounds:a.bounds})],{type:'image/svg+xml'})),l=document.createElement('a');l.href=u;l.download=a.id+'-'+theme+'.svg';l.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};card.append(art,h,p,b);$('grid').append(card);}$('stats').textContent=list.length+' matching assets · named IDs remain stable across films';$('page').textContent=(page+1)+' / '+Math.max(1,Math.ceil(list.length/limit));$('prev').disabled=page===0;$('next').disabled=(page+1)*limit>=list.length;}
$('query').oninput=()=>{page=0;render()};$('category').onchange=()=>{page=0;render()};$('theme').onchange=render;$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};render();
</script></html>`;
fs.writeFileSync(path.join(ROOT,'SHF_Asset_Catalog.html'),html);console.log('Catalog generated:',records.length);
